-- Create return requests table
CREATE TABLE public.return_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id BIGINT NOT NULL REFERENCES public.orders(id),
  user_id UUID REFERENCES auth.users(id),
  reason TEXT NOT NULL,
  reason_ar TEXT,
  refund_type TEXT NOT NULL DEFAULT 'money' CHECK (refund_type IN ('money', 'points')),
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected', 'completed')),
  admin_notes TEXT,
  refund_amount NUMERIC,
  refund_points INTEGER,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Create return settings table for admin control
CREATE TABLE public.return_settings (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  is_returns_enabled BOOLEAN DEFAULT true,
  allow_money_refund BOOLEAN DEFAULT true,
  allow_points_refund BOOLEAN DEFAULT true,
  return_window_days INTEGER DEFAULT 14,
  points_bonus_percentage NUMERIC DEFAULT 10,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT now()
);

-- Insert default settings
INSERT INTO public.return_settings (is_returns_enabled, allow_money_refund, allow_points_refund, return_window_days, points_bonus_percentage)
VALUES (true, true, true, 14, 10);

-- Enable RLS
ALTER TABLE public.return_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.return_settings ENABLE ROW LEVEL SECURITY;

-- RLS Policies for return_requests
CREATE POLICY "Users can create own return requests"
ON public.return_requests FOR INSERT
WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can view own return requests"
ON public.return_requests FOR SELECT
USING (auth.uid() = user_id);

CREATE POLICY "Admins can manage all return requests"
ON public.return_requests FOR ALL
USING (has_role(auth.uid(), 'admin'::app_role))
WITH CHECK (has_role(auth.uid(), 'admin'::app_role));

-- RLS Policies for return_settings
CREATE POLICY "Anyone can view return settings"
ON public.return_settings FOR SELECT
USING (true);

CREATE POLICY "Admins can manage return settings"
ON public.return_settings FOR ALL
USING (has_role(auth.uid(), 'admin'::app_role))
WITH CHECK (has_role(auth.uid(), 'admin'::app_role));

-- Update trigger
CREATE TRIGGER update_return_requests_updated_at
BEFORE UPDATE ON public.return_requests
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();

CREATE TRIGGER update_return_settings_updated_at
BEFORE UPDATE ON public.return_settings
FOR EACH ROW
EXECUTE FUNCTION public.update_updated_at_column();