// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qnwtpvuikcblrzemihej.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFud3RwdnVpa2NibHJ6ZW1paGVqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njg0MjQxMzIsImV4cCI6MjA4NDAwMDEzMn0.0BPkAz6Od0UNinHkYN2tdAfbT_6wwDSPMCykLpMNISQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});